### ISSUE TITLE
"Aborting process due to errors: String index out of range: -1"

### ISSUE THREAD

**Issue by dneise** [fact-project/fact-tools#151] opened 2016-10-17 08:36 UTC
While doing some raw data analysis on the FACT data cluster at ISDC, I encountered this error.

I would assume it might have something to do with the auxfiles ... not sure though.
An exception text, which clearly states what the error is, would be good.

```
java -jar -Xmx2500M -Xms2500M     /home/guest/neise/facttools_massive_production/single_photon_extractor/fact-tools-v0.16.0.jar     /home/guest/neise/facttools_massive_production/single_photon_extractor/analysis.xml     -DauxFolder=file:/fact/aux/2014/04/17/     -Doutfile=file:/scratch/fact/single_photon_extractor/json/2014/04/17/20140417_187.json     -Dinfile=file:/fact/raw/2014/04/17/20140417_187.fits.fz     -Ddrsfile=file:/fact/raw/2014/04/17/20140417_168.drs.fits.gz
Oct 14 2016 01:10:02 [ERROR] stream.io.SourceURL: Failed to register handler for protocol 'hdfs'
Oct 14 2016 01:10:02 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/prevEventAndSkip.xml'
Oct 14 2016 01:10:02 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/calibration.xml'
Oct 14 2016 01:10:02 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/extraction.xml'
Oct 14 2016 01:10:02 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/cleaning.xml'
Oct 14 2016 01:10:02 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/parameterCalc.xml'
Oct 14 2016 01:10:02 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/sourceParameter.xml'
Oct 14 2016 01:10:05 [INFO ] stream.runtime.ProcessContainer: ######## Sources ########
Oct 14 2016 01:10:05 [INFO ] stream.runtime.ProcessContainer: ########fact.io.zfits.ZFitsStream@bcbe4b0########
Oct 14 2016 01:10:05 [INFO ] stream.runtime.ProcessContainer:   ==> DefaultProcess['1']
Oct 14 2016 01:10:05 [INFO ] stream.runtime.ProcessContainer: ######## RootSources ########
Oct 14 2016 01:10:05 [INFO ] stream.runtime.ProcessContainer: fact.io.zfits.ZFitsStream@bcbe4b0
Oct 14 2016 01:10:05 [INFO ] stream.runtime.ProcessContainer: ######## NonRefSinks ########
Oct 14 2016 01:10:05 [INFO ] stream.runtime.ProcessContainer: ProcessContainer is initialized and ready to start:stream.runtime.ProcessContainer@14811a37
Oct 14 2016 01:10:05 [INFO ] stream.run: Starting process-container...
Oct 14 2016 01:10:05 [INFO ] fact.io.zfits.ZFitsStream: Reading file: /fact/raw/2014/04/17/20140417_187.fits.fz
Oct 14 2016 01:10:05 [INFO ] fact.io.zfits.ZFitsStream: File is ZFITS compresssed.
Oct 14 2016 01:10:05 [INFO ] fact.io.zfits.ZFitsStream: File contains ZDrsCellOffsets.
Oct 14 2016 01:10:05 [INFO ] stream.runtime.ProcessContainer: Initializing life-cycle objects...
Oct 14 2016 01:10:05 [INFO ] stream.runtime.ProcessContainer: Creating 1 active processes...
Oct 14 2016 01:10:07 [WARN ] fact.auxservice.AuxFileService$1: The file /fact/aux/2014/04/17 20140417.AGILENT_CONTROL_80V_STATE.fits is not a recognized aux service. 
Oct 14 2016 01:10:07 [WARN ] fact.auxservice.AuxFileService$1: The file /fact/aux/2014/04/17 20140417.MAGIC_LIDAR_STATE.fits is not a recognized aux service. 
Oct 14 2016 01:10:07 [WARN ] fact.auxservice.AuxFileService$1: The file /fact/aux/2014/04/17 20140417.MAGIC_LIDAR_DATA.fits is not a recognized aux service. 
Oct 14 2016 01:10:07 [WARN ] fact.auxservice.AuxFileService$1: The file /fact/aux/2014/04/17 20140417.MAGIC_LIDAR_MESSAGE.fits is not a recognized aux service. 
Oct 14 2016 01:10:07 [WARN ] fact.auxservice.AuxFileService$1: The file /fact/aux/2014/04/17 20140417.FEEDBACK_OFFSETS.fits is not a recognized aux service. 
Oct 14 2016 01:10:07 [ERROR] stream.runtime.AbstractProcess: Aborting process due to errors: String index out of range: -1
Oct 14 2016 01:10:07 [INFO ] stream.runtime.ProcessContainer$2: Process DefaultProcess['1'] finished!
Oct 14 2016 01:10:07 [INFO ] stream.run: Container finished.
```

**Comment by MaxNoe** [comment] 2016-10-17 10:03
I think this is a dupe of #71

**Closed** 2016-10-26 16:12 UTC
